name: Append Game Data

on:
  issues:
    types: [opened]

jobs:
  append:
    if: startsWith(github.event.issue.title, 'GameData:')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install xlsx

      - name: Save gameData to file
        run: echo '${{ github.event.issue.body }}' > game.json

      - name: Append data to Excel
        run: node .github/scripts/appendExcel.js

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git add data/war_game.xlsx
          git commit -m "Append new game data [skip ci]" || echo "No changes to commit"
          git push

      - name: Close the issue
        uses: peter-evans/close-issue@v2
        with:
          issue-number: ${{ github.event.issue.number }}
          comment: "Game data saved and issue closed ✅"
